name: cd

on:
  push:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # Force Node.js 24 for all actions

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.0

      - name: Set up Node
        uses: actions/setup-node@v4.3.1
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2.5.0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2.14.0

      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag us-central1-docker.pkg.dev/qwiklabs-gcp-02-99b6825c2250/notely-ar-repo/notely:latest .